use_frameworks!

target 'PyTorchTensorFlowCocoaPod_Example' do
  pod 'PyTorchTensorFlowCocoaPod', :path => '../'

  target 'PyTorchTensorFlowCocoaPod_Tests' do
    inherit! :search_paths

    
  end
end
